import "@/app/globals.css";
import { Metadata } from "next";
import { cairo } from "@/app/ui/fonts";
import Provider from "@/utils/Provider";
import { Providers } from "../providers";

export const metadata: Metadata = {
  title: "Nija Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`UI-Ecommerce ${cairo.className} antialiased`}>
        {/* <QueryClientProvider client={queryClient}> */}
        <Providers>{children}</Providers>
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
